# -*- makefile -*-
################################################################
################################################################
####
#### This Makefile belong with the sources
#### for The Art of HPC, volume 1: the Science of Computing
#### by Victor Eijkhout
#### copyright 2022
####
#### makefile for tikz plots
####
################################################################
################################################################

PUBLICFILES = "*.md5"
include ../makefiles/Make.public
include ../makefiles/Make.clean

clean :: basic_clean
